### ISSUE TITLE
 ERROR in Metadata version mismatch for module

### ISSUE THREAD

**Issue by ronaldofreitas** [atrixdigital/geo-realtime#1]
Your global Angular CLI version (1.6.4) is greater than your local
version (1.3.2). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Date: 2018-04-18T18:48:05.789Z                                                          
Hash: d14f719338562c1f281a
Time: 17981ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 14.2 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 221 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.3 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.33 MB [initial] [rendered]

ERROR in Metadata version mismatch for module /home/ronaldo/aplicativos/geomap/gmap-project/node_modules/angularfire2/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/ronaldo/aplicativos/geomap/gmap-project/src/app/app.module.ts, resolving symbol AppModule in /home/ronaldo/aplicativos/geomap/gmap-project/src/app/app.module.ts, resolving symbol AppModule in /home/ronaldo/aplicativos/geomap/gmap-project/src/app/app.module.ts

webpack: Failed to compile.

**Comment by moeidsaleem** [comment]
Quick Fix: 
ng serve 
if (Failed to compile ) => then go to app.module.ts and save the file again. The app will recompile and will run.


You will need to update both your angular-cli and Angularfire2 package.  This is because of incompatibility issue of angularfire2 module.
